# Generated by Django 4.1.5 on 2023-01-29 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webProjectApplication', '0002_alter_task_options_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
