# Generated by Django 4.1.5 on 2023-01-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webProjectApplication', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
